In [1]:
import torch

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [ ]:
# Is MPS even available? macOS 12.3+
print(torch.backends.mps.is_available())

# Was the current version of PyTorch built with MPS activated?
print(torch.backends.mps.is_built())

In [3]:
#Load from list
lst = [[1,2,3], [4,5,6]]
tensor = torch.tensor(lst)

#Load from NumPy array
np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)

NameError: name 'np' is not defined

In [ ]:
tensor.shape



torch.Size([2, 3])

In [6]:
tensor.dtype

torch.int64

In [7]:
tensor.device

device(type='cpu')

In [6]:
import torch.nn as nn

In [ ]:

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])


linear_layer = nn.Linear(in_features=3, out_features=2)


output = linear_layer(input_tensor)
print(output)



tensor([[-0.1719,  0.4617]], grad_fn=<AddmmBackward0>)


In [12]:
linear_layer.weight

Parameter containing:
tensor([[-0.5314, -0.2070, -0.1172],
        [ 0.3880,  0.0824,  0.5148]], requires_grad=True)

In [13]:
linear_layer.bias

Parameter containing:
tensor([0.0791, 0.4109], requires_grad=True)

In [14]:
#Create network with three linear layers
model = nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)

In [18]:
input_tensor = torch.tensor([[-0.0014, 0.4038, 1.0305, 0.07521, 0.7489, -0.3968, 0.0113, -1.3844, 0.08705, -0.9743]])
print(input_tensor)


tensor([[-0.0014,  0.4038,  1.0305,  0.0752,  0.7489, -0.3968,  0.0113, -1.3844,
          0.0870, -0.9743]])


In [19]:
#Pass input_tensor to model to obtain output
output_tensor = model(input_tensor)
print(output_tensor)

tensor([[-0.0797, -0.4895,  0.0066,  0.2236, -0.1330]],
       grad_fn=<AddmmBackward0>)


In [20]:
input_tensor = torch.tensor([6.0])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)

In [ ]:
 
print(output)

tensor([0.9975])


In [22]:
model = nn.Sequential(
    nn.Linear(6,4), #First linear layer
    nn.Linear(4,1), #Second linear layer
    nn.Sigmoid() #Sigmoid activation function
    )

In [23]:
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])

#Apply softmax along the last dimension
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)

print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [ ]:

input_data = torch.tensor([[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
                           [-0.9155, -0.0475, -1.3645, 0.6336, -1.9520, -0.3398],
                           [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633], 
                           [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
                           [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]])


In [ ]:

model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)

#Pass input data through model 
output = model(input_data)

In [8]:
print(output)

tensor([[0.4668],
        [0.3995],
        [0.4650],
        [0.3746],
        [0.4578]], grad_fn=<SigmoidBackward0>)


In [ ]:

n_classes = 3
#Create multiclass classification model
model=nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4, n_classes),
    nn.Softmax(dim=-1)
)
output = model(input_data)
print(output.shape)

torch.Size([5, 3])


In [ ]:
#Regression: forward pass
model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1)
)

output = model(input_data)

print(output)


tensor([[ 0.1692],
        [-0.1376],
        [-0.2210],
        [ 0.1542],
        [-0.0833]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

In [ ]:


import torch.nn.functional as F

F.one_hot(torch.tensor(0), num_classes = 3)

tensor([1, 0, 0])

In [5]:
F.one_hot(torch.tensor(1), num_classes = 3)

tensor([0, 1, 0])

In [6]:
F.one_hot(torch.tensor(2), num_classes = 3)

tensor([0, 0, 1])

In [ ]:


from torch.nn import CrossEntropyLoss

scores = torch.tensor([[-0.1211, 0.1059]])
one_hot_target = torch.tensor([[1,0]])
criterion = CrossEntropyLoss()
criterion(scores.double(), one_hot_target.double())



tensor(0.8131, dtype=torch.float64)

In [ ]:
y = 1
num_classes = 3

one_hot_numpy = np.array([0, 1, 0])

one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes=scores.shape[1])

In [ ]:
The first argument of F.one_hot() should be the ground truth label (in this case y), which should be converted to a tensor (e.g. using torch.tensor()) if it is not a tensor data type.
The second argument of F.one_hot() is num_classes, which is the number of features in the scores tensor and can be found by accessing the second dimension of the shape of scores (recall that .shape is zero-indexed).

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

In [ ]:

model = nn.Sequential(nn.Linear(16,8)
                      nn.Linear(8,4),
                      nn.Linear(4,2))
prediction = model(sample)

#Calculate the loss and compute the gradients
criterion = CrossEntropyLoss()
loss = criterion(prediction, target)
loss.Backward()

#Access each layer's gradients
model[0].weight.grad, model[0].bias.grad
model[1].weight.grad, model[0].bias.grad
model[2].weight.grad, model[0].bias.grad

In [ ]:

lr = 0.001

#Update the weights
weight = model[0].weight
weight_grad = model[0].weight.grad
weight = weight - lr * weight_grad

#Update the biases
bias = model[0].bias
bias_grad = model[0].bias.grad
bias = bias - lr * bias_grad

In [ ]:


import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.001)

optimizer.step()

In [ ]:
In previous exercises, you used linear layers to build networks.

Recall that the operation performed by nn.Linear() is to take an input 
 and apply the transformation 
 ,where 
 and 
 are two tensors (called the weight and bias).

A critical part of training PyTorch models is to calculate gradients of the weight and bias tensors with respect to a loss function.




In [ ]:
criterion = nn.CrossEntropyLoss()

loss = criterion(preds, target)

loss.backward()

print(weight.grad)
print(bias.grad)

In [ ]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Sigmoid(),
                      nn.Linear(8, 2))

weight_0 = model[0].weight

bias_1 = model[2].bias

In [ ]:
# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

In [ ]:

def mean_squared_loss(prediction, target):
    return np.mean((prediction - target)**2)
criterion = nn.MSELoss()
loss = criterion(prediction, target)


In [ ]:

dataset = TensorDataset(torch.tensor(features).float(), torch.tensor(target).float())
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

model = nn.Sequential(nn.Linear(4,2),
                      nn.Linear(2,1))

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.001)

for epoch in range(num_epochs):
    for data in dataloader:
        #Set the gradients to zero
        optimizer.zero_grad()
        #Get feature and target from the data loader
        feature, target = data
        #Run a forward pass
        pred = model(feature)
        #Compute loss and gradients
        loss = criterion(pred, target)
        loss.backward()
        #Update the parameters
        optimizer.step()

In [ ]:
y_hat = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_hat - y)**2)

# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())
print(mse_pytorch)

# Loop over the number of epochs and the dataloader
for i in range(num_epochs):
  for data in dataloader:
    # Set the gradients to zero
    optimizer.zero_grad()  
    # Run a forward pass
    feature, target = data
    prediction = model(feature)    
    # Calculate the loss
    loss = criterion(prediction, target)    
    # Compute the gradients
    loss.backward()
    # Update the model's parameters
    optimizer.step()
show_results(model, dataloader)

In [ ]:

relu = nn.ReLU()


leaky_relu = nn.LeakyReLU(negative_slope=0.05)



In [ ]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

In [ ]:
# Create a leaky relu function in PyTorch
leaky_relu_pytorch = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
# Call the above function on the tensor x
output = leaky_relu_pytorch(x)
print(output)

In [ ]:
#Layers are made of neurons
# - Linear layers are fully connected
# - Each neuron of a layer connected to each neuron of previous layer
# - A neuron of a linear layer: - computes a linear operation using all neurons of previous layer 
#                               - contains N+1 learnable parameters
#                               - where N = dimesion of previous layer's outputs

# Tewaking the number of hidden layers
# Input and output layers dimensions are fixed - input layer depends on the number of features n_features
#                                              - output layer depends on the number of categories n_classes
# We can use as many hidden layers as we want
# Increasing the number of hidden layers = increasing the number of parameters = increasing the model capacity


In [ ]:
#Counting the number of parameters 

model = nn.Sequential(nn.Linear(8,4),
                      nn.Linear(4,2))
#Manually calculating the number of parameters:
# - first layer has 4 neurons, each neuron has 8+1 parameters = 36 parameters
# - second layer has 2 neurons, each neuron has 4 + 1 parameters = 10 parameters
# total = 46 learnable parameters

# .numel(): returns the number of elements in the tensor

total = 0
for parameter in model.parameters()
    total += parameter.numel()
print(total)

In [ ]:
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with less than 120 parameters
model = nn.Sequential(nn.Linear(n_features, 8),
                      nn.Linear(8, 4),
                      nn.Linear(4, n_classes))
output = model(input_tensor)

In [ ]:
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with more than 120 parameters
model = nn.Sequential(nn.Linear(n_features, 16),
                      nn.Linear(16, 8),
                      nn.Linear(8, 3), 
                      nn.Linear(3, n_classes))

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.utilis.data import TensorDataset
from torch.utilis.data import DataLoader
pd.read_csv('animals.csv')
#Define input features
features = animals.iloc[:, 1:-1]
X = features.to_numpy()
print(X)

#Define target features (ground truth)

target = animals.iloc[:, -1]
y = target.to_numpy()

#Instatiate dataset class
dataset = TensorDataset(torch.tensor(X).float(), torch.tensor(y).float())

#Access an individual sample
sample = dataset[0]
input_sample, label_sample = sample
print('input sample:', input_sample)
print('label_sample:', label_sample)


batch_size = 2 # Kiedy bedziemy iterowac po module ladujacym dane, batch_size bedzie okreslac ile probek pobieramy ze zbioru w jednej iteracji.
               # Parametr shuffle informuje moduł ładujący dane o tasowaniu danych w kazdej iteracji.
shuffle = True

#Create a DataLoader
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

#Iterate over the dataloader
for batch_inputs, batch_labels in dataloader:
    print('batch inputs', batch_inputs)
    print('batch labels', batch_labels)



In [ ]:


training_loss = 0.0
for i, data in enumerate(trainloader, 0):
    # Run the forward pass
    ...
    # Calculate the loss
    loss = criterion(outputs, labels)
    # Calculate the gradients
    ...
    # Calculate and sum the loss
    training_loss += loss.item()
epoch_loss = training_loss / len(trainloader)


In [10]:
#Calculating validation loss
#After the training epoch, we iterate over the validation set and calculate the average validation loss
validation_loss = 0.0
model.eval() # Put model in evaluation mode
with torch.no_grad(): #Speed up the forward pass
    for i, data in enumerate(validationloader, 0):
        #Run the forward pass
        ...
        #Calculate the loss
        loss = criterion(outputs, labels)
        validation_loss += loss.item()
epoch_loss = validation_loss / len(validationloader)
model.train()

In [ ]:
#Calculating accuracy with torchmetrics
import torchmetrics
#Create accuracy metric using torch metrics
metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
for i, data in enumerate(dataloader, 0):
    features, labels = data
    outputs = model(features)
    # Calculate accuracy over the batch
    acc = metric(output, labels.argmax(dim=-1))

# Calculate accuracy over the whole epoch
acc = metric.compute()
print(f"Accuracy on all data: {acc}")
#Reset the metric for the next epoch (training or validation)
metric.reset()



In [ ]:


model = nn.Sequential(nn.Linear(8,4),
                      nn.ReLU(),
                      nn.Dropout(p=0.5)) # tutaj ustawiamy 50% tensora wyjsciowego na zero

features = torch.randn((1,8))
model(i)



In [ ]:
#Regularization with weight decay
optimizer = optim.SGD(model.parameters(), lr = 1e-3, weight_decay=1e-4)


In [ ]:
#Improving model performance

#fine-tune hyperparameters
#Grid search
for factor in range(2,6):
    lr = 10 ** -factor
#Random search
factor = np.random.uniform(2,6)
lr = 10 ** -factor
